// constants/styles.ts

import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: Platform.OS === 'android' ? 40 : 20,
    paddingHorizontal: 20,
    backgroundColor: '#0D1117',
  },
  logo: {
    width: '80%',
    height: 150,
    alignSelf: 'center',
    marginTop: 20,
    marginBottom: 20,
  },
  logoutButton: {
    position: 'absolute',
    top: Platform.OS === 'android' ? 25 : 35,
    right: 20,
    zIndex: 10,
  },
  logoutIcon: {
    width: 40,
    height: 40,
    tintColor: '#9b5de5',
  },
  sectionTitle: {
    textAlign: 'center',
    fontSize: 35,
    fontWeight: 'bold',
    color: '#E6EDF3',
    marginBottom: 5,
    fontFamily: 'monospace',
  },
  separator: {
    height: 3,
    backgroundColor: '#444',
    marginVertical: 0,
    alignSelf: 'center',
    width: '110%',
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    gap: 10,
    paddingBottom: 100,
  },
  noteCard: {
    width: '30%',
    borderRadius: 12,
    paddingVertical: 20,
    alignItems: 'center',
    marginBottom: 10,
  },
  iconPlaceholder: {
    width: 80,
    height: 90,
    borderRadius: 12,
    backgroundColor: '#161B22',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
    overflow: 'hidden',
  },
  noteImage: {
    width: 60,
    height: 70,
    tintColor: '#E6EDF3',
  },
  noteCardTitle: {
    color: '#E6EDF3',
    fontWeight: '600',
    fontSize: 14,
    textAlign: 'center',
    marginTop: 4,
    fontFamily: 'monospace',
  },
  addButton: {
    width: 60,
    height: 60,
    paddingBottom: 30,
    borderRadius: 12,
    position: 'absolute',
    bottom: 20,
    right: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  darkContainer: {
    flex: 1,
    paddingTop: 10,
    paddingHorizontal: 20,
    backgroundColor: '#0D1117',
  },
  editHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  backButton: {
    padding: 5,
  },
  titleInput: {
    height: 50,
    flex: 1,
    fontSize: 26,
    fontWeight: 'bold',
    color: '#E6EDF3',
    marginLeft: 5,
  },
  textArea: {
    backgroundColor: 'transparent',
    color: '#E6EDF3',
    padding: 10,
    textAlignVertical: 'top',
    flex: 1,
    fontSize: 16,
    lineHeight: 24,
  },
  starIcon: {
    width: 30,
    height: 30,
    tintColor: '#9b5de5',
    marginLeft: 20,
  },
  authContainer: {
    flex: 1,
    backgroundColor: '#0D1117',
    justifyContent: 'center',
    padding: 20,
  },
  authLogo: {
    width: '80%',
    height: 150,
    alignSelf: 'center',
    marginBottom: 50,
  },
  authInput: {
    backgroundColor: 'transparent',
    color: '#E6EDF3',
    borderWidth: 1,
    borderColor: '#E6EDF3',
    borderRadius: 12,
    paddingHorizontal: 15,
    paddingVertical: 12,
    fontSize: 16,
    marginBottom: 20,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 15,
  },
  authButton: {
    backgroundColor: '#9b5de5',
    paddingVertical: 15,
    borderRadius: 8,
    alignItems: 'center',
    flex: 1,
  },
  authButtonFull: {
    backgroundColor: '#9b5de5',
    paddingVertical: 15,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 20,
  },
  authButtonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  authLink: {
    color: '#58A6FF',
    textAlign: 'center',
    marginTop: 0,
  },
  signupRedirectContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 'auto',
    paddingBottom: 20,
  },
  signupRedirectText: {
    color: '#AAA',
    fontSize: 14,
  },
  signupRedirectLink: {
    color: '#9b5de5',
    fontSize: 14,
    fontWeight: 'bold',
    marginLeft: 5,
  },

  // ===== ESTILOS DAS ABAS QUE ESTAVAM FALTANDO =====
  topTabsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 15,
    marginBottom: 25,
    width: '100%',
  },
  tabButton: {
    paddingVertical: 10,
    paddingHorizontal: 25,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: '#30363D',
  },
  activeTabButton: {
    backgroundColor: '#9b5de5',
    borderColor: '#9b5de5',
  },
  tabButtonText: {
    color: '#AAA',
    fontWeight: '600',
    fontSize: 14,
  },
  activeTabButtonText: {
    color: '#FFF',
  },
  // ===================================================

  favoriteStarIcon: {
    position: 'absolute',
    top: 10,
    right: 0,
    width: 20,
    height: 20,
    zIndex: 1,
  },
  authInstructionText: {
    color: '#AAA',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 30,
    paddingHorizontal: 15,
  },
  backToLoginLink: {
    color: '#58A6FF',
    textAlign: 'center',
    marginTop: 20,
    fontSize: 16,
  },
});

export default styles;